[package]
name = "matrix_mult_strassen"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Vinícius Vargas <santunionivinicius@gmail.com>"]
description = "Strassen algorithm for matrix multiplication"

[dev-dependencies]

[dependencies]
thiserror = "2.0.12"