[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"


[[bench]]
name = "benchmark"
harness = false


[dev-dependencies]
criterion = "0.5.1"

[profile.dev]
opt-level = 0 # The default for dev

[profile.release]
opt-level = 3 # The default for release