[package]
name = "grokking"
version = "0.1.0"
edition = "2024"

[dependencies]
tailcall = "1.0.1"

[dev-dependencies]
bacon = "3.12.0"
criterion = "0.5.1"



[[bench]]
name = "chapter_3_tail_factorial"
harness = false