bin = [
    { name = "selection_sort", path = "src/chapter2/selection_sort.rs" },
]

[package]
name = "grokking"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
bacon = "3.12.0"
